import { useState } from 'react';
import { ArrowLeft, Bike, CheckCircle2, MapPin, Navigation, Phone } from 'lucide-react';
import { Link } from 'react-router-dom';

const initialDeliveries = [
  { id: '88214', customer: 'Maya Rivera', address: '42 Nebula Avenue', driver: 'Sam K.', status: 'Out for delivery', eta: '12 min' },
  { id: '88211', customer: 'Alex Thomas', address: '8 Moonstone Street', driver: 'Unassigned', status: 'Ready for dispatch', eta: '--' },
  { id: '88208', customer: 'Jordan Kim', address: '105 Stardust Road', driver: 'Nora P.', status: 'Delivered', eta: 'Done' },
];

const Delivery = () => {
  const [deliveries, setDeliveries] = useState(initialDeliveries);
  const assignDriver = id => setDeliveries(prev => prev.map(item => item.id === id ? { ...item, driver: 'Nora P.', status: 'Out for delivery', eta: '18 min' } : item));
  return <div className="min-h-screen bg-[#0b0d12] text-white"><header className="border-b border-white/10 px-6 lg:px-10 py-5 flex items-center gap-4"><Link to="/admin" className="p-2 rounded-lg hover:bg-white/5"><ArrowLeft className="w-5 h-5" /></Link><div><p className="text-xs uppercase tracking-[0.25em] text-brand-primary">Gravity Ops</p><h1 className="text-2xl font-display">Delivery control</h1></div></header><main className="p-6 lg:p-10 max-w-7xl mx-auto"><div className="grid sm:grid-cols-3 gap-4 mb-8"><Metric label="Active deliveries" value="1" /><Metric label="Ready to dispatch" value="1" /><Metric label="Available drivers" value="4" /></div><section className="bg-white/[0.03] border border-white/10 rounded-2xl overflow-hidden"><div className="p-6 flex justify-between"><div><h2 className="text-xl font-bold">Delivery queue</h2><p className="text-sm text-text-dim">Assign and monitor every drop</p></div><Bike className="text-brand-primary" /></div><div className="divide-y divide-white/10">{deliveries.map(item => <div key={item.id} className="p-6 flex flex-wrap items-center gap-5"><div className="w-11 h-11 rounded-xl bg-brand-primary/15 flex items-center justify-center text-brand-primary font-bold">#{item.id.slice(-2)}</div><div className="min-w-[180px] flex-1"><strong>{item.customer}</strong><p className="text-sm text-text-dim"><MapPin className="inline w-3 h-3 mr-1" />{item.address}</p></div><div className="text-sm min-w-[150px]"><p className="text-text-dim">Driver</p><p>{item.driver}</p></div><div className="text-sm min-w-[150px]"><p className="text-text-dim">Status</p><p className={item.status === 'Delivered' ? 'text-green-400' : 'text-brand-primary'}>{item.status}</p></div><div className="text-sm text-text-dim min-w-[80px]">{item.eta}</div>{item.status === 'Ready for dispatch' && <button onClick={() => assignDriver(item.id)} className="px-4 py-2 rounded-lg bg-brand-primary text-xs font-bold">Assign driver</button>}{item.status === 'Delivered' && <CheckCircle2 className="text-green-400" />}</div>)}</div></section><div className="mt-8 grid md:grid-cols-2 gap-6"><div className="bg-white/[0.03] border border-white/10 rounded-2xl p-6"><Navigation className="text-brand-primary mb-5" /><h2 className="text-xl font-bold mb-2">Driver coverage</h2><p className="text-text-dim text-sm">All active zones are covered. Average delivery time is 22 minutes.</p></div><div className="bg-white/[0.03] border border-white/10 rounded-2xl p-6"><Phone className="text-brand-primary mb-5" /><h2 className="text-xl font-bold mb-2">Customer support</h2><p className="text-text-dim text-sm">No delivery issues reported during the current service window.</p></div></div></main></div>;
};

const Metric = ({ label, value }) => <div className="bg-white/[0.03] border border-white/10 rounded-2xl p-5"><span className="text-3xl font-bold">{value}</span><p className="text-sm text-text-dim mt-1">{label}</p></div>;
export default Delivery;